### ISSUE TITLE
explain why 10gbps upload is required in the docs and/or faq

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/L1-node#108] opened 2022-11-14 23:09 UTC
this comes up over and over again. best to address it head on

one idea:

* add a note after the  

    > 10Gbps upload link minimum
    
    line of https://github.com/filecoin-saturn/L1-node#nodes-host-requirements, like
    
    > 10Gbps upload link minimum ([Why 10Gbps?](/docs/faq.md#why-10gbps))
    
* add an entry to the faq that explains why 10gbps is the upload requirement

* link the note to the new faq page entry

we could/should also note that the 10gbps can be burstable; 10gbps dedicated isnt required

the things to note:
1. many users around the world have 1gbps download. it only takes a handful of 1gbps users to saturate and monopolize a 1gbps upload server
2. better to start high and lower than start low and raise. with the latter, we'd have to kick nodes from the network
3. we're looking into adjusting server requirements based on geography, knowing 10gbps is not the same price around the world

if i (@gruns) have time, ill whip up the faq answer and add it

**Comment by 464hee** [comment] 2022-11-15 02:04
But isn't your idea to let more ordinary people participate in the network construction of Filecoin? How do ordinary families have 10Gbps upload bandwidth?I think your starting point is right, but now the threshold is no different from the storage provider.I think that compared with 10Gbps upload bandwidth, the capacity of the hard disk is not too large for ordinary home users, Because 18T hard disk is far less expensive than 10Gbps broadband.

**Comment by 464hee** [comment] 2022-11-15 02:20
I really recommend you to look at some of the edge computing services in China that require as little as 10Mbps upload. Although it is small, it is deployed by a large number of people. I believe there are some technologies that can reasonably solve the problem of user download speed caused by low broadband. What is the specific way.Here is the link to the product: 

https://item.m.jd.com/product/100017678229.html?utm_user=plusmember&gx=RnFjxjIKaTWKyNRP--tyC69lf_Shcj-dndRC&ad_od=share& utm_source=androidapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=CopyURL

**Comment by 464hee** [comment] 2022-11-15 02:24
hope to bring you some useful references

**Comment by gruns** [comment] 2022-11-15 05:13
hey @464hee! thank you for weighing in

saturn l1s are meant to be large servers in datacenters. theyre not intended for family/residential/fixed internet connections, theyre intended to run in datacenters with fast upload speeds

saturn l2s (https://github.com/filecoin-saturn/L2-node), which havent launched yet, are intended for home residential internet connections where 10mbps upload is more common

i hope that helps!

**Comment by 464hee** [comment] 2022-11-15 05:45
ok,Thank you for your work. I look forward to that day.

**Comment by typoworx-de** [comment] 2022-11-15 10:37
> saturn l1s are meant to be large servers in datacenters. theyre not intended for family/residential/fixed internet connections, theyre intended to run in datacenters with fast upload speeds

Well I have 40 TB server in datacenter with 1 Gbit Uplink. I also intended to install filecoin and there nowhere was any info that such a large uplink is required! This is a really non-usual setup even for datacenter hosted machines. I fully agree that family/residental/fixed internet connection should be no option for such node/servers! But I won't upgrade to expensive 10 GBps uplink just for being able to fullyfill such idealistic wishes to filecoin.

I think 1 GBps upwards should be the preference for that. Everything else will lead to less nodes. And to be honest the estimate for rewards (see https://strn.network/#calculateyourearnings) is the biggest joke of the year keeping in mind what 10 GBps uplink costs per month. Just noticed the calculator is the only point where 10 GBps uplink is even mentioned in the small printed text.

**Comment by PiotrStyla** [comment] 2022-11-16 18:02
> > saturn l1s are meant to be large servers in datacenters. theyre not intended for family/residential/fixed internet connections, theyre intended to run in datacenters with fast upload speeds
> 
> Well I have 40 TB server in datacenter with 1 Gbit Uplink. I also intended to install filecoin and there nowhere was any info that such a large uplink is required! This is a really non-usual setup even for datacenter hosted machines. I fully agree that family/residental/fixed internet connection should be no option for such node/servers! But I won't upgrade to expensive 10 GBps uplink just for being able to fullyfill such idealistic wishes to filecoin.
> 
> I think 1 GBps upwards should be the preference for that. Everything else will lead to less nodes. And to be honest the estimate for rewards (see https://strn.network/#calculateyourearnings) is the biggest joke of the year keeping in mind what 10 GBps uplink costs per month. Just noticed the calculator is the only point where 10 GBps uplink is even mentioned in the small printed text.
> 
> And even the rewards are for a laugh considering the montly costs for a dedicated server with 10 GBps uplink. I don't even think one can make a small profit on that it's not worth it with this requirement.

Thank you @typoworx-de  - yes I strongly recommend reconsidering this requirement. I have been using VPNs in data centers to trade forex and for WordPress installs and it is rare to find one with such high upload speed.
For small players taking a financial risk of tens of hundreds of euros is not the way of building the community I believe.
I would appreciate it if anyone could share a few reliable and not expensive data centers with this high bandwidth speed - thank you in advance.

**Comment by guchengdaoke** [comment] 2022-11-17 06:34
> > saturn l1s are meant to be large servers in datacenters. theyre not intended for family/residential/fixed internet connections, theyre intended to run in datacenters with fast upload speeds
> 
> Well I have 40 TB server in datacenter with 1 Gbit Uplink. I also intended to install filecoin and there nowhere was any info that such a large uplink is required! This is a really non-usual setup even for datacenter hosted machines. I fully agree that family/residental/fixed internet connection should be no option for such node/servers! But I won't upgrade to expensive 10 GBps uplink just for being able to fullyfill such idealistic wishes to filecoin.
> 
> I think 1 GBps upwards should be the preference for that. Everything else will lead to less nodes. And to be honest the estimate for rewards (see https://strn.network/#calculateyourearnings) is the biggest joke of the year keeping in mind what 10 GBps uplink costs per month. Just noticed the calculator is the only point where 10 GBps uplink is even mentioned in the small printed text.
> 
> And even the rewards are for a laugh considering the montly costs for a dedicated server with 10 GBps uplink. I don't even think one can make a small profit on that it's not worth it with this requirement.

yes
Most of the data centers in Europe and the United States do not count the hardware. The 10Gbps network alone needs 1000+ per month. Some even 2000+
so
The income of the calculator is a joke. What is even more ridiculous is that it is still a theoretical value. The actual income is actually lower.

**Comment by gruns** [comment] 2022-11-18 01:40
> The actual income is actually lower.

its early days for saturn, and earnings will rise :)

**Comment by PiotrStyla** [comment] 2022-11-18 06:47
> its early days for saturn; earnings will rise 🙂

Could you please tell when the first payouts happen as it is said that the are done monthly?

**Comment by guchengdaoke** [comment] 2022-11-18 07:16
> > The actual income is actually lower.
> 
> its early days for saturn; earnings will rise 🙂

Now the official communication community
Don't have a discord?

**Comment by PiotrStyla** [comment] 2022-11-18 11:36
> Now the official communication community Don't have a discord? 
No, Slack only could you please send me an invite link? Thank you

**Comment by guchengdaoke** [comment] 2022-11-18 12:07
> > Now the official communication community Don't have a discord?
> > No, Slack only could you please send me an invite link? Thank you

There is indeed no discord on the official website
I'm also waiting for the official opening of the discord

**Comment by DiegoRBaquero** [comment] 2022-11-18 15:08
> > its early days for saturn; earnings will rise 🙂
> 
> Could you please tell when the first payouts happen as it is said that the are done monthly?

End of november

> > > Now the official communication community Don't have a discord?
> > > No, Slack only could you please send me an invite link? Thank you
> 
> There is indeed no discord on the official website I'm also waiting for the official opening of the discord

There are no plans to open a discord. Please join us in [#filecoin-saturn slack channel](https://filecoinproject.slack.com/archives/C03DH0BL02E)

**Closed** 2022-11-18 16:47 UTC
Labels: enhancement

**Comment by gruns** [comment] 2022-11-18 21:16
> I'm also waiting for the official opening of the discord

be sure to jump into #filecoin-saturn on filecoin slack! 🙌 

as diego mentioned above, here's the link to join that channel: https://filecoinproject.slack.com/archives/C03DH0BL02E

**Comment by guchengdaoke** [comment] 2022-12-02 07:41
> > its early days for saturn; earnings will rise 🙂
> 
> Could you please tell when the first payouts happen as it is said that the are done monthly?

Excuse me, have you settled the income yet? It is already December 2nd
